on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build

jobs:
  checking:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dev dependencies
        run: |
          echo ${{github.ref}}
          apt-get install python3-setuptools
          pip install pytest black mypy pytest-asyncio pytest-cov pytest-black pytest-mypy
          pip install requests fastapi uvicorn
          pip install -e .

      - name: Run Tests
        run: python setup.py test
      - uses: codecov/codecov-action@v1
        with:
          file: ./reports/coverage.xml 
          flags: unittests 
          fail_ci_if_error: true 
          verbose: true 

  releasing:  
    name: Build Release
    runs-on: ubuntu-latest
    needs: checking
    if:  github.ref == 'refs/heads/main' 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dev dependencies
        run: |
          pip install black bumpversion mkdocs mkdocs-material wheel 
      - name: Bump version
        run: bumpversion patch setup.py monads/__init__.py
      - name: Build docs
        run:  mkdocs build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./site
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
        


          

